language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgtk2.0-dev libgtkglextmm-x11-1.2-dev libgtkmm-2.4-dev
  - sudo apt-get install python-dev
  - sudo apt-get install libboost-python-dev libboost-signals-dev
  - sudo apt-get install libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev
  - sudo apt-get install python-wxgtk2.8 python-wxtools wx2.8-i18n libwxgtk2.8-dev libgtk2.0-dev
# wxPython needs access to the X display, otherwise it will raise a SystemExit
# we need to "imitate" a monitor
# more info: http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" 
install:
  - "pip install -r requirements.txt"
  - "pip install ."
# install dependencies
install: 
  - pip install -r requirements.txt
# run tests via pytest
script: 
  - python ./tests/runtests.py
